#' Volcano Plot for Metabolomics Differential Analysis
#'
#' @description
#' Generates a volcano plot from differential expression results produced by
#' a limma-based analysis (e.g., from `metabol.diff()`). The plot highlights
#' significantly up- and down-regulated metabolites and optionally labels the
#' top most significant features.
#'
#' @details
#' The function accepts either:
#' \itemize{
#'   \item an explicit `limma_results` list containing a `results` data frame, or
#'   \item an object produced by `metabol.diff()` that stores results in
#'         `normalized_data$limma_results`.
#' }
#'
#' Required columns in the results table are `"Metabolite"`, `"logFC"`, and
#' `"P.Value"`.
#'
#' Metabolites are classified as:
#' \itemize{
#'   \item **Up** — `P.Value < p_thresh` and `logFC >= fc_thresh`
#'   \item **Down** — `P.Value < p_thresh` and `logFC <= -fc_thresh`
#'   \item **NS** — non-significant
#' }
#'
#' The function also highlights the top `top_labels` metabolites ranked by
#' smallest p-value.
#'
#' @param normalized_data Optional object containing a `limma_results` field.
#'   Typically the output of `metabol.diff()`. Used only when `limma_results`
#'   is not supplied.
#' @param limma_results A list containing a `results` data frame, usually
#'   extracted from `metabol.diff()`. Overrides `normalized_data$limma_results`.
#' @param p_thresh Numeric p-value threshold used to define significance.
#'   Default is `0.05`.
#' @param fc_thresh Minimum absolute log fold-change used to classify points as
#'   up- or down-regulated. Default is `0.5`.
#' @param top_labels Number of most significant metabolites to label in the
#'   plot. Default is `5`.
#' @param title Character title for the plot.
#'
#' @return
#' Invisibly returns the `ggplot` object after printing it.
#'
#' @examples
#' \dontrun{
#' # Using object generated by metabol.diff()
#' metabol.volcano(my_norm)
#'
#' # Providing limma_results manually
#' metabol.volcano(limma_results = my_norm$limma_results)
#'
#' # Custom thresholds
#' metabol.volcano(my_norm, p_thresh = 0.01, fc_thresh = 1)
#' }
#'
#' @importFrom dplyr case_when arrange
#' @importFrom ggplot2 ggplot aes geom_point geom_text geom_vline geom_hline
#'   theme_minimal labs scale_color_manual theme
#'
#' @export

metabol.volcano <- function(
    normalized_data = NULL,
    limma_results = NULL,
    p_thresh = 0.05,
    fc_thresh = 0.5,
    top_labels = 5,
    title = "Volcano plot"
) {

  # ------------------------------------------------------------
  # 0) Detect limma results automatically
  # ------------------------------------------------------------
  if (is.null(limma_results)) {
    if (!is.null(normalized_data$limma_results)) {
      limma_results <- normalized_data$limma_results
    } else {
      stop("No limma results found. Provide limma_results or an object containing them.")
    }
  }

  if (!is.list(limma_results) || is.null(limma_results$results)) {
    stop("limma_results must be a list containing a 'results' data.frame.")
  }

  df <- limma_results$results

  # ------------------------------------------------------------
  # 1) Required columns
  # ------------------------------------------------------------
  needed_cols <- c("Metabolite", "logFC", "P.Value")
  if (!all(needed_cols %in% colnames(df))) {
    stop("limma_results$results must contain columns: Metabolite, logFC, P.Value.")
  }

  # ------------------------------------------------------------
  # 2) Prepare data
  # ------------------------------------------------------------
  df$neglogP <- -log10(df$P.Value)

  df$status <- dplyr::case_when(
    df$P.Value < p_thresh & df$logFC >= fc_thresh  ~ "Up",
    df$P.Value < p_thresh & df$logFC <= -fc_thresh ~ "Down",
    TRUE                                           ~ "NS"
  )

  df$status <- base::factor(df$status, levels = c("Up", "Down", "NS"))

  cores <- c(
    "Up"   = "#E64B35FF",
    "Down" = "#4DBBD5FF",
    "NS"   = "gray70"
  )

  # ------------------------------------------------------------
  # 3) Top labels (safe subset)
  # ------------------------------------------------------------
  df_ord <- dplyr::arrange(df, .data$P.Value)
  n_top <- min(top_labels, nrow(df_ord))
  top_df <- df_ord[seq_len(n_top), , drop = FALSE]

  # ------------------------------------------------------------
  # 4) Volcano Plot
  # ------------------------------------------------------------
  g <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = .data$logFC,
      y = .data$neglogP,
      color = .data$status
    )
  ) +
    ggplot2::geom_point(alpha = 0.8, size = 2) +
    ggplot2::scale_color_manual(values = cores) +

    ggplot2::geom_vline(
      xintercept = c(-fc_thresh, fc_thresh),
      linetype = "dashed",
      color = "gray40"
    ) +
    ggplot2::geom_hline(
      yintercept = -log10(p_thresh),
      linetype = "dashed",
      color = "gray40"
    ) +

    ggplot2::geom_text(
      data = top_df,
      ggplot2::aes(label = .data$Metabolite),
      size = 3.5,
      vjust = -0.5,
      color = "black"
    ) +

    ggplot2::theme_minimal(base_size = 12) +
    ggplot2::labs(
      title = title,
      x = "log2 Fold Change",
      y = "-log10(p-value)",
      color = ""
    ) +
    ggplot2::theme(
      legend.position = "top"
    )

  # explicit print()
  print(g)
  invisible(g)
}
